set(CMAKE_ASM_VASM_SOURCE_FILE_EXTENSIONS s)

if(NOT CMAKE_ASM_VASM_COMPILE_OBJECT)
  set(CMAKE_ASM_VASM_COMPILE_OBJECT "<CMAKE_ASM_VASM_COMPILER> <INCLUDES> -phxass -Fhunk -quiet -m68020 -no-opt -o <OBJECT> <SOURCE>")
endif()

set(ASM_DIALECT "_VASM")
include(CMakeASMInformation)
set(ASM_DIALECT)
